spring.datasource.url=jdbc:postgresql://dpg-d7e4k1f7f7vs73ecd9i0-a:5432/banco_db_2e28
spring.datasource.username=banco_db_2e28_user
spring.datasource.password=tjOrvAqYrwfL7EMHj3mP0n1QULhNkMox

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false